from typing import Protocol

from contract.models.actions import AuditEntry
from contract.models.autonomy import Trust
from contract.models.business import BusinessProfile
from contract.models.learning import Lesson
from contract.models.schedules import Schedule
from contract.models.tasks import Approval, Task
from contract.models.team import Team
from contract.models.usage import ModelUsage

class Store(Protocol):
    async def get_profile(self, business_id: str) -> BusinessProfile | None: ...
    async def save_profile(self, profile: BusinessProfile) -> None: ...

    async def save_team(self, team: Team) -> None: ...
    async def get_team(self, team_id: str) -> Team | None: ...
    async def list_teams(self, business_id: str) -> list[Team]: ...
    async def get_trust(self, team_id: str, task_type: str) -> Trust | None: ...
    async def set_trust(self, trust: Trust) -> None: ...

    async def save_task(self, task: Task) -> None: ...
    async def get_task(self, task_id: str) -> Task | None: ...
    async def save_approval(self, approval: Approval) -> None: ...
    async def get_approval(self, approval_id: str) -> Approval | None: ...
    async def recent_approvals(
        self, team_id: str, task_type: str, limit: int = 5
    ) -> list[Approval]: ...

    async def save_lesson(self, lesson: Lesson) -> None: ...
    async def list_lessons(
        self, business_id: str, team_id: str | None, task_type: str | None = None
    ) -> list[Lesson]: ...

    async def log_action(self, entry: AuditEntry) -> None: ...
    async def get_action(self, action_id: str) -> AuditEntry | None: ...

    async def log_usage(self, usage: ModelUsage) -> None: ...

    async def save_schedule(self, schedule: Schedule) -> None: ...
    async def get_schedule(self, schedule_id: str) -> Schedule | None: ...
    async def list_schedules(
        self, business_id: str, team_id: str | None = None
    ) -> list[Schedule]: ...
