from typing import Protocol

from pydantic import BaseModel

from contract import Approval, AuditEntry, Lesson, Store, Task, Trust

class TelegramTopic(BaseModel):
    team_id: str
    business_id: str
    chat_id: int
    thread_id: int
    name: str

class AppStore(Store, Protocol):
    """
    The contract Store plus what only the app needs: businesses, their Telegram links,
    dashboard links, and the queries behind the dashboard.
    """

    async def create_business(self, chat_id: int) -> str: ...
    async def list_businesses(self) -> dict[int, str]: ...
    async def save_topic(self, topic: TelegramTopic) -> None: ...
    async def list_topics(self) -> list[TelegramTopic]: ...
    async def dashboard_token(self, business_id: str) -> str: ...
    async def business_for_token(self, token: str) -> str | None: ...
    async def list_trust(self, team_id: str) -> list[Trust]: ...
    async def list_tasks(self, business_id: str, limit: int = 50) -> list[Task]: ...
    async def list_approvals(
        self, business_id: str, status: str | None = None, limit: int = 100
    ) -> list[Approval]: ...
    async def list_actions(self, business_id: str, limit: int = 50) -> list[AuditEntry]: ...
    async def list_all_lessons(self, business_id: str) -> list[Lesson]: ...
