from datetime import datetime
from typing import Any, Protocol

from pydantic import BaseModel

from contract import Approval, AuditEntry, Lesson, Store, Task, Trust

class TelegramTopic(BaseModel):
    team_id: str
    business_id: str
    chat_id: int
    thread_id: int
    name: str

class AppStore(Store, Protocol):
    """
    The contract Store plus what only the app needs: businesses, their Telegram links,
    dashboard links, the queries behind the dashboard, and removing a replaced team
    (its topic link, trust, tasks, approvals and team lessons; the audit log stays).
    """

    async def create_business(self, chat_id: int) -> str: ...
    async def list_businesses(self) -> dict[int, str]: ...
    async def save_topic(self, topic: TelegramTopic) -> None: ...
    async def list_topics(self) -> list[TelegramTopic]: ...
    async def dashboard_token(self, business_id: str) -> str | None: ...
    async def set_dashboard(
        self, business_id: str, token: str | None, password_hash: str | None
    ) -> None: ...
    async def dashboard_access(self, token: str) -> tuple[str, str] | None: ...
    async def list_trust(self, team_id: str) -> list[Trust]: ...
    async def list_tasks(self, business_id: str, limit: int = 50) -> list[Task]: ...
    async def list_approvals(
        self, business_id: str, status: str | None = None, limit: int = 100
    ) -> list[Approval]: ...
    async def list_actions(self, business_id: str, limit: int = 50) -> list[AuditEntry]: ...
    async def list_all_lessons(self, business_id: str) -> list[Lesson]: ...
    async def delete_team(self, team_id: str) -> None: ...
    async def save_state(self, kind: str, key: str, data: Any) -> None: ...
    async def delete_state(self, kind: str, key: str) -> None: ...
    async def list_state(self) -> list[tuple[str, str, Any]]: ...
    async def prune_state(self, before: datetime) -> None: ...
